import { Badge } from "~/components/ui/badge";
import { Button } from "~/components/ui/button";
import { ButtonGroup, ButtonGroupItem } from "~/components/ui/button-group";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "~/components/ui/card";
import { Container } from "~/components/ui/container";
import { Icon } from "~/components/ui/icon";
import { IconButton } from "~/components/ui/icon-button";
import { GuideGroup, SectionHeader } from "./layout";

export function FoundationsSection() {
	return (
		<GuideGroup id="style-guide-group-foundations" title="Foundations" description="Core building blocks, state markers, and surface rules used across the whole UI system.">
			<section className="space-y-4" data-testid="style-guide-button"><SectionHeader title="Button" description="Primary action control. Use the shared button variants for calls to action, secondary actions, and low-emphasis inline controls." /><Card><CardContent className="flex flex-wrap items-center gap-3 pt-6"><Button>Primary action</Button><Button variant="secondary">Secondary</Button><Button variant="outline">Outline</Button><Button variant="ghost">Ghost</Button><Button variant="destructive">Destructive</Button><Button variant="link">Link style</Button></CardContent></Card></section>
			<section className="space-y-4" data-testid="style-guide-button-group"><SectionHeader title="Button Group" description="Grouped related actions into a single compact control. Use it when actions belong together and should read as one set instead of separate loose buttons." /><Card><CardContent className="flex flex-wrap items-center gap-3 pt-6"><ButtonGroup><ButtonGroupItem>Comment</ButtonGroupItem><ButtonGroupItem>Share</ButtonGroupItem></ButtonGroup><ButtonGroup><ButtonGroupItem>Day</ButtonGroupItem><ButtonGroupItem>Week</ButtonGroupItem><ButtonGroupItem>Month</ButtonGroupItem></ButtonGroup></CardContent></Card></section>
			<section className="space-y-4" data-testid="style-guide-icon"><SectionHeader title="Icon" description="Single icon wrapper for all Lucide usage in the product. Use this component instead of importing icons route-by-route." /><Card><CardContent className="flex flex-wrap items-center gap-4 pt-6"><div className="flex items-center gap-2 rounded-lg border border-border px-3 py-2"><Icon name="home" /><span className="text-sm">Home</span></div><div className="flex items-center gap-2 rounded-lg border border-border px-3 py-2"><Icon name="bell" /><span className="text-sm">Alerts</span></div><div className="flex items-center gap-2 rounded-lg border border-border px-3 py-2"><Icon name="settings" /><span className="text-sm">Settings</span></div><div className="flex items-center gap-2 rounded-lg border border-border px-3 py-2"><Icon name="grid2x2" /><span className="text-sm">Layout</span></div></CardContent></Card></section>
			<section className="space-y-4" data-testid="style-guide-icon-button"><SectionHeader title="Icon Button" description="Compact action control for icon-only affordances. Use it when the icon is clear, the action is small, and an accessible label is supplied." /><Card><CardContent className="flex flex-wrap items-center gap-3 pt-6"><IconButton label="Add image" variant="ghost"><Icon name="imagePlus" size={16} /></IconButton><IconButton label="Attach file" variant="outline"><Icon name="paperclip" size={16} /></IconButton><IconButton label="Send reply"><Icon name="sendHorizontal" size={16} /></IconButton></CardContent></Card></section>
			<section className="space-y-4" data-testid="style-guide-badge"><SectionHeader title="Badge" description="Small state indicator for moderation, visibility, and status. Use badges when the UI needs compact state markers without turning them into full pills or buttons." /><Card><CardContent className="flex flex-wrap items-center gap-3 pt-6"><Badge>Hidden</Badge><Badge variant="neutral">Draft</Badge><Badge variant="success">Approved</Badge><Badge variant="warning">Flagged</Badge><Badge variant="danger">Rejected</Badge></CardContent></Card></section>
			<section className="space-y-4" data-testid="style-guide-container"><SectionHeader title="Container" description="Base surface wrapper for navigation rails, composer shells, post blocks, and sidebar utilities when the UI only needs one consistent border-and-shadow treatment." /><Container className="space-y-4 rounded-lg border-border/50 bg-card p-5" data-testid="style-guide-container"><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary">Feed</Button><Button size="sm" variant="ghost">Groups</Button><Button size="sm" variant="ghost">Notifications</Button></div><div className="rounded-xl border border-border/70 p-4"><p className="text-sm leading-7 text-foreground">Use the same container around post cards, side menus, and composer shells so the surface language stays consistent.</p></div></Container></section>
			<section className="space-y-4" data-testid="style-guide-card"><SectionHeader title="Card" description="Default content container for grouped information, internal panels, guide sections, and compositional feature blocks." /><Card><CardHeader><CardTitle>Community overview</CardTitle><CardDescription>Cards provide a reliable header-content-footer structure for future product surfaces.</CardDescription></CardHeader><CardContent className="space-y-3"><p className="text-sm leading-7 text-muted-foreground">Use cards when a block needs clear hierarchy, breathing room, and a consistent border/surface treatment.</p><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-muted/50 p-3 text-sm"><p className="font-medium">Members</p><p className="mt-1 text-muted-foreground">128 active</p></div><div className="rounded-lg bg-muted/50 p-3 text-sm"><p className="font-medium">Groups</p><p className="mt-1 text-muted-foreground">14 public spaces</p></div><div className="rounded-lg bg-muted/50 p-3 text-sm"><p className="font-medium">Moderation</p><p className="mt-1 text-muted-foreground">Healthy baseline</p></div></div></CardContent><CardFooter><Button size="sm">Open dashboard</Button><Button size="sm" variant="outline">Learn more</Button></CardFooter></Card></section>
			<section className="space-y-4" data-testid="style-guide-elevation"><SectionHeader title="Elevation" description="Shared depth system with three levels. Most components should stay on low elevation and only move up when hierarchy genuinely needs it." /><div className="grid gap-4 lg:grid-cols-3"><div className="elevation-low rounded-lg border border-border bg-card p-4"><p className="text-sm font-medium text-foreground">Low</p><p className="mt-2 text-sm text-muted-foreground">Default for cards, bubbles, navigation, and everyday surfaces.</p></div><div className="elevation-medium rounded-lg border border-border bg-card p-4"><p className="text-sm font-medium text-foreground">Medium</p><p className="mt-2 text-sm text-muted-foreground">Use sparingly for feature surfaces such as heroes or highlighted content.</p></div><div className="elevation-high rounded-lg border border-border bg-card p-4"><p className="text-sm font-medium text-foreground">High</p><p className="mt-2 text-sm text-muted-foreground">Reserve for overlays, urgent layers, or future modal-level UI.</p></div></div></section>
		</GuideGroup>
	);
}
