// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/auth/hub/login": {
    params: {};
  };
  "/auth/hub/callback": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/metrics": {
    params: {};
  };
  "/debug/error-monitoring": {
    params: {};
  };
  "/setup": {
    params: {};
  };
  "/database-required": {
    params: {};
  };
  "/feed": {
    params: {};
  };
  "/community": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/server-settings": {
    params: {};
  };
  "/audit-logs": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/auth/hub/login" | "/auth/hub/callback" | "/api/auth/*" | "/metrics" | "/debug/error-monitoring" | "/setup" | "/database-required" | "/feed" | "/community" | "/profile" | "/notifications" | "/settings" | "/server-settings" | "/audit-logs";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/hub-login.tsx": {
    id: "routes/hub-login";
    page: "/auth/hub/login";
  };
  "routes/hub-callback.tsx": {
    id: "routes/hub-callback";
    page: "/auth/hub/callback";
  };
  "routes/api-auth.ts": {
    id: "routes/api-auth";
    page: "/api/auth/*";
  };
  "routes/metrics.tsx": {
    id: "routes/metrics";
    page: "/metrics";
  };
  "routes/debug-error-monitoring.tsx": {
    id: "routes/debug-error-monitoring";
    page: "/debug/error-monitoring";
  };
  "routes/setup.tsx": {
    id: "routes/setup";
    page: "/setup";
  };
  "routes/database-required.tsx": {
    id: "routes/database-required";
    page: "/database-required";
  };
  "routes/feed.tsx": {
    id: "routes/feed";
    page: "/feed";
  };
  "routes/community.tsx": {
    id: "routes/community";
    page: "/community";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/notifications.tsx": {
    id: "routes/notifications";
    page: "/notifications";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/server-settings.tsx": {
    id: "routes/server-settings";
    page: "/server-settings";
  };
  "routes/audit-logs.tsx": {
    id: "routes/audit-logs";
    page: "/audit-logs";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/hub-login": typeof import("./app/routes/hub-login.tsx");
  "routes/hub-callback": typeof import("./app/routes/hub-callback.tsx");
  "routes/api-auth": typeof import("./app/routes/api-auth.ts");
  "routes/metrics": typeof import("./app/routes/metrics.tsx");
  "routes/debug-error-monitoring": typeof import("./app/routes/debug-error-monitoring.tsx");
  "routes/setup": typeof import("./app/routes/setup.tsx");
  "routes/database-required": typeof import("./app/routes/database-required.tsx");
  "routes/feed": typeof import("./app/routes/feed.tsx");
  "routes/community": typeof import("./app/routes/community.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/notifications": typeof import("./app/routes/notifications.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/server-settings": typeof import("./app/routes/server-settings.tsx");
  "routes/audit-logs": typeof import("./app/routes/audit-logs.tsx");
};