// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/auth/hub/login": {
    params: {};
  };
  "/auth/hub/callback": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/api/post-list": {
    params: {};
  };
  "/api/search": {
    params: {};
  };
  "/api/notifications/summary": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/media/:assetId/:variantKey": {
    params: {
      "assetId": string;
      "variantKey": string;
    };
  };
  "/profile-images/:userId": {
    params: {
      "userId": string;
    };
  };
  "/profile-images/:userId/:size": {
    params: {
      "userId": string;
      "size": string;
    };
  };
  "/metrics": {
    params: {};
  };
  "/up": {
    params: {};
  };
  "/debug/error-monitoring": {
    params: {};
  };
  "/setup": {
    params: {};
  };
  "/database-required": {
    params: {};
  };
  "/style-guide": {
    params: {};
  };
  "/feed": {
    params: {};
  };
  "/community": {
    params: {};
  };
  "/posts/:postId": {
    params: {
      "postId": string;
    };
  };
  "/groups": {
    params: {};
  };
  "/groups/:groupId": {
    params: {
      "groupId": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/profiles": {
    params: {};
  };
  "/profiles/:userId": {
    params: {
      "userId": string;
    };
  };
  "/notifications": {
    params: {};
  };
  "/approvals": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/server-settings": {
    params: {};
  };
  "/audit-logs": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/auth/hub/login" | "/auth/hub/callback" | "/api/auth/*" | "/api/post-list" | "/api/search" | "/api/notifications/summary" | "/.well-known/appspecific/com.chrome.devtools.json" | "/media/:assetId/:variantKey" | "/profile-images/:userId" | "/profile-images/:userId/:size" | "/metrics" | "/up" | "/debug/error-monitoring" | "/setup" | "/database-required" | "/style-guide" | "/feed" | "/community" | "/posts/:postId" | "/groups" | "/groups/:groupId" | "/profile" | "/profiles" | "/profiles/:userId" | "/notifications" | "/approvals" | "/settings" | "/server-settings" | "/audit-logs";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/hub-login.tsx": {
    id: "routes/hub-login";
    page: "/auth/hub/login";
  };
  "routes/hub-callback.tsx": {
    id: "routes/hub-callback";
    page: "/auth/hub/callback";
  };
  "routes/api-auth.ts": {
    id: "routes/api-auth";
    page: "/api/auth/*";
  };
  "routes/api-post-list.tsx": {
    id: "routes/api-post-list";
    page: "/api/post-list";
  };
  "routes/api-search.tsx": {
    id: "routes/api-search";
    page: "/api/search";
  };
  "routes/api-notifications-summary.tsx": {
    id: "routes/api-notifications-summary";
    page: "/api/notifications/summary";
  };
  "routes/chrome-devtools-workspace.ts": {
    id: "routes/chrome-devtools-workspace";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/media-asset.ts": {
    id: "routes/media-asset";
    page: "/media/:assetId/:variantKey";
  };
  "routes/profile-image.ts": {
    id: "routes/profile-image";
    page: "/profile-images/:userId";
  };
  "routes/profile-image-size.ts": {
    id: "routes/profile-image-size";
    page: "/profile-images/:userId/:size";
  };
  "routes/metrics.tsx": {
    id: "routes/metrics";
    page: "/metrics";
  };
  "routes/up.ts": {
    id: "routes/up";
    page: "/up";
  };
  "routes/debug-error-monitoring.tsx": {
    id: "routes/debug-error-monitoring";
    page: "/debug/error-monitoring";
  };
  "routes/setup.tsx": {
    id: "routes/setup";
    page: "/setup";
  };
  "routes/database-required.tsx": {
    id: "routes/database-required";
    page: "/database-required";
  };
  "routes/style-guide.tsx": {
    id: "routes/style-guide";
    page: "/style-guide";
  };
  "routes/feed.tsx": {
    id: "routes/feed";
    page: "/feed";
  };
  "routes/community.tsx": {
    id: "routes/community";
    page: "/community";
  };
  "routes/post-detail.tsx": {
    id: "routes/post-detail";
    page: "/posts/:postId";
  };
  "routes/groups.tsx": {
    id: "routes/groups";
    page: "/groups";
  };
  "routes/group-detail.tsx": {
    id: "routes/group-detail";
    page: "/groups/:groupId";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/profile-list.tsx": {
    id: "routes/profile-list";
    page: "/profiles";
  };
  "routes/profile-detail.tsx": {
    id: "routes/profile-detail";
    page: "/profiles/:userId";
  };
  "routes/notifications.tsx": {
    id: "routes/notifications";
    page: "/notifications";
  };
  "routes/approvals.tsx": {
    id: "routes/approvals";
    page: "/approvals";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/server-settings.tsx": {
    id: "routes/server-settings";
    page: "/server-settings";
  };
  "routes/audit-logs.tsx": {
    id: "routes/audit-logs";
    page: "/audit-logs";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/hub-login": typeof import("./app/routes/hub-login.tsx");
  "routes/hub-callback": typeof import("./app/routes/hub-callback.tsx");
  "routes/api-auth": typeof import("./app/routes/api-auth.ts");
  "routes/api-post-list": typeof import("./app/routes/api-post-list.tsx");
  "routes/api-search": typeof import("./app/routes/api-search.tsx");
  "routes/api-notifications-summary": typeof import("./app/routes/api-notifications-summary.tsx");
  "routes/chrome-devtools-workspace": typeof import("./app/routes/chrome-devtools-workspace.ts");
  "routes/media-asset": typeof import("./app/routes/media-asset.ts");
  "routes/profile-image": typeof import("./app/routes/profile-image.ts");
  "routes/profile-image-size": typeof import("./app/routes/profile-image-size.ts");
  "routes/metrics": typeof import("./app/routes/metrics.tsx");
  "routes/up": typeof import("./app/routes/up.ts");
  "routes/debug-error-monitoring": typeof import("./app/routes/debug-error-monitoring.tsx");
  "routes/setup": typeof import("./app/routes/setup.tsx");
  "routes/database-required": typeof import("./app/routes/database-required.tsx");
  "routes/style-guide": typeof import("./app/routes/style-guide.tsx");
  "routes/feed": typeof import("./app/routes/feed.tsx");
  "routes/community": typeof import("./app/routes/community.tsx");
  "routes/post-detail": typeof import("./app/routes/post-detail.tsx");
  "routes/groups": typeof import("./app/routes/groups.tsx");
  "routes/group-detail": typeof import("./app/routes/group-detail.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/profile-list": typeof import("./app/routes/profile-list.tsx");
  "routes/profile-detail": typeof import("./app/routes/profile-detail.tsx");
  "routes/notifications": typeof import("./app/routes/notifications.tsx");
  "routes/approvals": typeof import("./app/routes/approvals.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/server-settings": typeof import("./app/routes/server-settings.tsx");
  "routes/audit-logs": typeof import("./app/routes/audit-logs.tsx");
};